# Generated by Django 4.1.1 on 2022-09-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_categories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
