# Generated by Django 4.1.1 on 2022-09-28 22:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_entry_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='_content_rendered',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='content_markup_type',
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
